
 export default palabras = [
        {
            id:'1',
            palabra:'Cheque',
            descripcion:[
                {
                    id:'1',
                    significado:'despedirse',
                    tipo:'interjección'
                },
                {
                    id:'2',
                    significado:'todo esta bien',
                    tipo:'adverbio'
                }                
            ]
        },
        {
            id:'2',
            palabra:'Alero',
            descripcion:[
                {
                    id:'1',
                    significado:'amigo',
                    tipo:'sustantivo'
                }                
            ]
        },
        {
            id:'3',
            palabra:'Yuca',
            descripcion:[
                {
                    id:'1',
                    significado:'algo difícil',
                    tipo:'adverbio'
                }                
            ]
        },
        {
            id:'4',
            palabra:'Simón',
            descripcion:[
                {
                    id:'1',
                    significado:'así es',
                    tipo:'interjección'
                }                
            ]
        },
        {
            id:'5',
            palabra:'Alucinar',
            descripcion:[
                {
                    id:'1',
                    significado:'presumir',
                    tipo:'verbo'
                }                
            ]
        },
        {
            id:'6',
            palabra:'Agüevar',
            descripcion:[
                {
                    id:'1',
                    significado:'avergonzar',
                    tipo:'verbo'
                }                
            ]
        },
        {
            id:'7',
            palabra:'Choco',
            descripcion:[
                {
                    id:'1',
                    significado:'que no ve bien',
                    tipo:'adjetivo'
                },
                {
                    id:'2',
                    significado:'ciego',
                    tipo:'adjetivo'
                }                                
            ]
        },
        {
            id:'8',
            palabra:'Pucha',
            descripcion:[
                {
                    id:'1',
                    significado:'asombrado',
                    tipo:'interjección'
                }                
            ]
        },    
        {
            id:'9',
            palabra:'Raite',
            descripcion:[
                {
                    id:'1',
                    significado:'pasaje gratis',
                    tipo:'verbo'
                }                
            ]
        },
        {
            id:'10',
            palabra:'Güirro',
            descripcion:[
                {
                    id:'1',
                    significado:'niño',
                    tipo:'verbo'
                }                
            ]
        },
        {
            id:'11',
            palabra:'Nambe',
            descripcion:[
                {
                    id:'1',
                    significado:'rechazar la acción o la expressión de otro',
                    tipo:'interjección'
                }                
            ]
        },
        {
            id:'12',
            palabra:'Maje',
            descripcion:[
                {
                    id:'1',
                    significado:'persona muy tonta',
                    tipo:'adverbio'
                },
                {
                    id:'2',
                    significado:'papo',
                    tipo:'adverbio'
                },
                {
                    id:'3',
                    significado:'tosco',
                    tipo:'adverbio'
                },                                
                {
                    id:'4',
                    significado:'maule',
                    tipo:'adverbio'
                },                                
                {
                    id:'5',
                    significado:'gilada',
                    tipo:'adverbio'
                },                                
            ]
        },
        {
            id:'13',
            palabra:'Chami',
            descripcion:[
                {
                    id:'1',
                    significado:'camisa',
                    tipo:'sustantivo'
                }
            ]
        },
        {
            id:'14',
            palabra:'Chante',
            descripcion:[
                {
                    id:'1',
                    significado:'casa',
                    tipo:'sustantivo'
                }
            ]
        },
        {
            id:'15',
            palabra:'Braco',
            descripcion:[
                {
                    id:'1',
                    significado:'persona enojado que no le importa los demás',
                    tipo:'adjetivo'
                }
            ]
        },
        {
            id:'16',
            palabra:'Chamba',
            descripcion:[
                {
                    id:'1',
                    significado:'trabajo',
                    tipo:'sustantivo'
                }
            ]
        },
        {
            id:'17',
            palabra:'Paja',
            descripcion:[
                {
                    id:'1',
                    significado:'casaca',
                    tipo:'adjetivo'
                },
                {
                    id:'2',
                    significado:'mentira',
                    tipo:'adjetivo'
                }
            ]
        },
        {
            id:'18',
            palabra:'Calar',
            descripcion:[
                {
                    id:'1',
                    significado:'pegar una pedrara',
                    tipo:'verbo'
                }
            ]
        },
        {
            id:'19',
            palabra:'Chunche',
            descripcion:[
                {
                    id:'1',
                    significado:'cosa',
                    tipo:'sustantivo'
                }
            ]
        },
        {
            id:'20',
            palabra:'Dundo',
            descripcion:[
                {
                    id:'1',
                    significado:'bruto',
                    tipo:'verbo'
                }
            ]
        },
        {
            id:'21',
            palabra:'Mínimo',
            descripcion:[
                {
                    id:'1',
                    significado:'banano',
                    tipo:'verbo'
                }
            ]
        },
        {
            id:'23',
            palabra:'Pisto',
            descripcion:[
                {
                    id:'1',
                    significado:'dinero',
                    tipo:'sustantivo'
                }
            ]
        },
        {
            id:'24',
            palabra:'Desmangado',
            descripcion:[
                {
                    id:'1',
                    significado:'ir con mucha prisa',
                    tipo:'verbo'
                }
            ]
        }
    ]
